export { ReLU } from './ReLU';
export { Func } from './types';
export { Logistic } from './Logistic';
export { Areasinus } from './Areasinus';
export { UnitLinear } from './UnitLinear';
export { ZeroLinear } from './ZeroLinear';
export { RationalSigmoid } from './RationalSigmoid';
export { FadingOscillator } from './FadingOscillator';
export { HyperbolicTangent } from './HyperbolicTangent';
